---
name: New Feature Report
description: Thanks for taking time to fill out this report!
title: "[Feature:] "
labels: "[]"
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweenwattana
    validations:
        required: true

  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this report!
        
  - type: dropdown
    id: New_Feature
    attributes:
      label: Version
      description: Type of request?
      options:
        - New Feature
        - Bug
        - Issue
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: os_selection
    attributes:
      label: What is the OS which you want to suggest?
      description: Selections
      options:
        - Mac 
        - Linux
        - Android
        - Steam OS
        - Windows
  - type: textarea
    id: details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Feature details!
    validations:
      requireds: true
---
